version: '2'
services:
  redis:
    image: "redis:alpine"
  postgres:
    image: "postgres:14.0"
    environment:
     POSTGRES_PASSWORD: p@ssw0rd42
     POSTGRES_USER: postgres
     POSTGRES_DB: postgres
  web:
    build: .
    ports:
     - "80:3500"
    volumes:
     - .:/usr/src/app
    environment:
      DB_HOST: postgres
      REDIS_HOST: redis
    depends_on:
      - postgres
      - redis
    command: ["./wait_for_it.sh", "postgres:5432", "--", "npm", "start"]